service: tenisliga-chat-v2

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

  chatkitAuth:
    handler: serverless/chatkitAuth.authenticate
    events:
      - http:
          path: api/authenticate
          method: post

  chatkitCreateUser:
    handler: serverless/chatkitUsers.createUser
    events:
      - http:
          path: api/createUser
          method: post

  chatkitDeleteUser:
    handler: serverless/chatkitUsers.deleteUser
    events:
      - http:
          path: api/deleteUser
          method: post

plugins:
  - serverless-apigw-binary

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'